In [2]:
from sklearn import datasets
import pandas as pd
import numpy as np

# Загрузка основной инфы для ирисов
iris = datasets.load_iris()
print(iris)
# Создаём двумерную таблицу, и вставляем инфу о длине\ширине чашелистика, и о длине\ширине лепестка
iris_frame = pd.DataFrame(iris.data)
# Подписываем индексы
iris_frame.columns = iris.feature_names

# Добавляем столбец с целевой переменной (0 - setosa, 1 - versicolor, 2 - virginica)
iris_frame['target'] = iris.target
# Для наглядности добавляем столбец с сортами
iris_frame['name'] = iris_frame.target.apply(lambda x: iris.target_names[x])

#iris_frame

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [2]:
alpha = 0.00003

weight_1_2 = np.random.randn(4, 4)
weight_2_3 = np.random.randn(4, 4)
weight_3_4 = np.random.randn(4, 4)
weight_4_5 = np.random.randn(4, 1)

print(weight_1_2, weight_2_3, weight_3_4, weight_4_5, sep="\n\n")

[[ 1.16054136 -1.05644028  0.52971442 -0.84238071]
 [ 2.26394945  1.49426941  0.75195188  1.64402921]
 [-0.28458654 -1.14568917  0.54316564 -0.36342075]
 [ 0.0921968  -0.54177657  0.26726524 -0.47214936]]

[[ 0.16314118  0.04374249  1.41243426 -2.8135857 ]
 [-0.68052871  1.03439456  0.47834903  0.55243532]
 [-0.10306842 -0.57055062  0.70162162 -0.30746884]
 [ 0.41524132 -0.02560832 -0.75104105  1.96995806]]

[[-0.67950895 -0.71710945  1.51589747  0.17714679]
 [ 1.64163432 -0.3902997   0.50589237  0.97970217]
 [-0.2860645  -0.04872755 -2.15266782  0.74217851]
 [ 0.51176507  0.12228455 -0.77670581 -0.61917399]]

[[ 0.16106065]
 [-0.63282358]
 [ 0.5305212 ]
 [-1.04640627]]


In [ ]:
for iteration in range(250):
    for i in range(len(iris_frame["sepal length (cm)"])):
        inp = [iris_frame["sepal length (cm)"][i], iris_frame["sepal width (cm)"][i], iris_frame["petal length (cm)"][i], iris_frame["petal width (cm)"][i]]
        goal_pred = iris_frame["target"][i]
        
        layer_2 = np.dot(inp, weight_1_2)
        layer_3 = np.dot(layer_2, weight_2_3)
        layer_4 = np.dot(layer_3, weight_3_4)
        pred = np.sum(np.dot(layer_4, weight_4_5))
        if iteration % 100 == 0:
            if pred <= 0.5:
                print("It is a - setosa", goal_pred, pred)
            elif pred > 0.7 and pred <= 1.5:
                print("It is a - versicolor", goal_pred, pred)
            elif pred > 1.7 and pred <= 2.5:
                print("It is a - virginica", goal_pred, pred)
            else:
                print("I dont know", goal_pred, pred)

        error = (pred - goal_pred) ** 2
        layer_5_delta = pred - goal_pred
        layer_4_delta = np.sum(np.dot(layer_5_delta, weight_4_5))
        layer_3_delta = np.sum(np.dot(layer_4_delta, weight_3_4))
        layer_2_delta = np.sum(np.dot(layer_3_delta, weight_2_3))

        weight_delta_1_2 = np.zeros(weight_1_2.shape)
        weight_delta_2_3 = np.zeros(weight_2_3.shape)
        weight_delta_3_4 = np.zeros(weight_3_4.shape)
        weight_delta_4_5 = np.zeros(weight_4_5.shape)

        for k in range(len(weight_delta_1_2)):
            for j in range(len(weight_delta_1_2[k])):
                weight_delta_1_2[k][j] = inp[k] * layer_2_delta   

        for k in range(len(weight_delta_2_3)):
            for j in range(len(weight_delta_2_3[k])):
                weight_delta_2_3[k][j] = np.sum(layer_2.T[j]) * layer_3_delta

        for k in range(len(weight_delta_3_4)):
            for j in range(len(weight_delta_3_4[k])):
                weight_delta_3_4[k][j] = np.sum(layer_3.T[j]) * layer_4_delta

        for k in range(len(weight_delta_4_5)):
            weight_delta_4_5[k] = np.sum(layer_4.T[k]) * layer_5_delta


        for k in range(len(weight_1_2)):
            for j in range(len(weight_1_2)):
                weight_1_2[k][j] -= weight_delta_1_2[k][j] * alpha

        for k in range(len(weight_2_3)):
            for j in range(len(weight_2_3)):
                weight_2_3[k][j] -= weight_delta_2_3[k][j] * alpha

        for k in range(len(weight_3_4)):
            for j in range(len(weight_3_4)):
                weight_3_4[k][j] -= weight_delta_3_4[k][j] * alpha

        for k in range(len(weight_4_5)):     
            weight_4_5[k] -= weight_delta_4_5[k] * alpha
            
    print(iteration, error, sep=" --- ")

In [11]:
for i in range(len(iris_frame["sepal length (cm)"])):
        inp = [iris_frame["sepal length (cm)"][i], iris_frame["sepal width (cm)"][i], iris_frame["petal length (cm)"][i], iris_frame["petal width (cm)"][i]]
        goal_pred = iris_frame["target"][i]
        
        layer_2 = np.dot(inp, weight_1_2)
        layer_3 = np.dot(layer_2, weight_2_3)
        layer_4 = np.dot(layer_3, weight_3_4)
        pred = np.sum(np.dot(layer_4, weight_4_5))
        if pred <= 0.5:
            print("It is a - setosa", goal_pred, pred)
        elif pred > 0.5 and pred <= 1.7:
            print("It is a - versicolor", goal_pred, pred)
        elif pred > 1.7:
            print("It is a - virginica", goal_pred, pred)
        else:
            print("I dont know", goal_pred, pred)

It is a - setosa 0 -0.004040424180493218
It is a - setosa 0 0.052764114064569156
It is a - setosa 0 0.007786133728707512
It is a - setosa 0 0.08875293489072256
It is a - setosa 0 -0.009735043311410507
It is a - setosa 0 0.11871674826140932
It is a - setosa 0 0.06248872126638716
It is a - setosa 0 0.04333763490747522
It is a - setosa 0 0.08274282684450718
It is a - setosa 0 0.040060455399260064
It is a - setosa 0 -0.002077665075780999
It is a - setosa 0 0.08502107486453525
It is a - setosa 0 0.020261030339121078
It is a - setosa 0 -0.06026845117551538
It is a - setosa 0 -0.14825919128119125
It is a - setosa 0 -0.009312623073270743
It is a - setosa 0 -0.015638220034801975
It is a - setosa 0 0.03251000848645802
It is a - setosa 0 0.07976623684234596
It is a - setosa 0 0.03687284634327881
It is a - setosa 0 0.0943257232895629
It is a - setosa 0 0.08316524708263628
It is a - setosa 0 -0.1279006158415985
It is a - setosa 0 0.225861036187343
It is a - setosa 0 0.18578730108669816
It is a - se